Repository ProyectoIntegrador2018/blue-lab, pull requests merged in 2020-02, with the labels that each got.

#65 Conexion de los numeros de Home page con Backend
  showroom/src/components/Numbers.vue
Labels: Sprint 3, user story

#80 Rud database
  showroom_api/src/controllers/items.js
  showroom_api/src/controllers/similarcalls.js
  showroom_api/src/controllers/urls.js
  showroom_api/src/routes/routes-mongo.js
Labels: Sprint 3

#83 Refactor SearchBar
  showroom/package-lock.json
  showroom/src/components/CardItem.vue
  showroom/src/components/SearchBar.vue
Labels: Sprint 3, done, task

#85 Add Contact to Url Model
  showroom_api/src/controllers/urls.js
  showroom_api/src/models/url.js
Labels: Sprint 3, done, task

#86 Details with proy
  showroom/package-lock.json
  showroom/src/App.vue
  showroom/src/components/API_Items.vue
  showroom/src/components/CardItem.vue
  showroom/src/components/DetailsItem.vue
  showroom/src/components/NavBar.vue
Labels: Sprint 3

#87 Refactor del Navbar
  showroom/src/components/Header.vue
  showroom/src/components/NavBar.vue
  showroom/src/components/SearchBar.vue
Labels: Sprint 3, done, task

#88 Changes URL and Details
  showroom/src/components/DetailsItem.vue
  showroom/src/store/index.js
Labels: Sprint 3, done, task

#91 Agregar animacion de contar hacia arriba a los numeros del HomePage
  showroom/package-lock.json
  showroom/package.json
  showroom/src/components/Numbers.vue
  showroom/src/main.js
Labels: Sprint 3, done, task
