Repository ProyectoIntegrador2018/blue-lab, pull requests merged in 2020-01, with the labels that each got.

#2 Readme and Template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  INTERVIEW_TEMPLATE.md
  README.md
Labels: documentation

#41 Actualizacion Readme
  README.md
Labels: documentation

#42 setup inicial vue cli
  showroom/.browserslistrc
  showroom/.eslintrc.js
  showroom/.gitignore
  showroom/README.md
  showroom/babel.config.js
  showroom/package-lock.json
  showroom/package.json
  showroom/public/favicon.ico
  showroom/public/index.html
  showroom/src/App.vue
  showroom/src/assets/logo.png
  showroom/src/components/HelloWorld.vue
  showroom/src/main.js
  showroom/src/router/index.js
  showroom/src/store/index.js
  showroom/src/views/About.vue
  showroom/src/views/Home.vue
Labels: Sprint 2

#43 Top nav bar
  showroom/src/App.vue
  showroom/src/assets/blueppl.png
  showroom/src/assets/css/bootstrap.css
  showroom/src/main.js
Labels: Sprint 2

#44 Top nav bar
  showroom/src/App.vue
  showroom/src/assets/BPLogoTAG_RGB-72dpi_Ver01-Blanco.png
  showroom/src/assets/wallpaper.jpg
Labels: Sprint 2

#47 Read, Delete, Update database
  showroom_api/src/controllers/items.js
  showroom_api/src/routes.js
Labels: Sprint 2

#55 Deployment y ReadMe update
  DEPLOYMENT.md
  README.md
  package-lock.json
Labels: Sprint 2, documentation, done

#62 Routes administration
  showroom_api/package-lock.json
  showroom_api/package.json
  showroom_api/src/controllers/items.js
  showroom_api/src/controllers/similarcalls.js
  showroom_api/src/controllers/urls.js
  showroom_api/src/models/url.js
  showroom_api/src/routes/routes-mongo.js
Labels: Sprint 3

#64 Api calls front
  showroom/package-lock.json
  showroom/package.json
  showroom/src/App.vue
  showroom/src/components/API_Items.vue
  showroom/src/components/Numbers.vue
  showroom/src/store/index.js
  showroom_api/package.json
  showroom_api/src/services/file-upload.js
Labels: Sprint 3, task
